## Arithmetic
#### Import package

In [1]:
import numpy as np

#### Basic statistics of NumPy array
`max(axis), mean(axis), min(axis), std(axis), sum(axis), var(axis)`: 0 for column, 1 for row (default: all elements)

In [2]:
np.array([5, 10, 15]).std()

4.0824829046386304

`np.max(x), np.mean(x), np.min(x), np.std(x), np.sum(x), np.var(x)`

In [3]:
np.max(np.array([[5, 10, 15], [10, 15, 5]]), axis=0)

array([10, 15, 15])

#### Basic statistics of NumPy array (NaN safe)
`np.nanmax(x), np.nanmean(x), np.nanmin(x), np.nanstd(x), np.nansum(x), np.nanvar(x)`

In [4]:
np.nanmean(np.array([1, np.nan, 3]))

2.0

#### Pairwise calculation
`a + b, a - b, a * b, a / b, a ** b, a % b`

In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a + b, a - b, a * b, a / b, a ** b, a % b

(array([5, 7, 9]),
 array([-3, -3, -3]),
 array([ 4, 10, 18]),
 array([ 0.25,  0.4 ,  0.5 ]),
 array([  1,  32, 729]),
 array([1, 2, 3]))

`np.add(a, b), np.subtract(a, b), np.multiply(a, b), np.divide(a, b), np.power(a, b), np.mod(a, b)`

In [6]:
np.add(a, b), np.subtract(a, b), np.multiply(a, b), np.divide(a, b), np.power(a, b), np.mod(a, b)

(array([5, 7, 9]),
 array([-3, -3, -3]),
 array([ 4, 10, 18]),
 array([ 0.25,  0.4 ,  0.5 ]),
 array([  1,  32, 729]),
 array([1, 2, 3]))

#### Pairwise comparison
`a == b, a != b, a < b, a <= b, a > b, a >= b`

In [7]:
np.array([5, 10, 15]) <= np.array([15, 10 ,5])

array([ True,  True, False], dtype=bool)

`np.equal(a, b), np.not_equal(a, b), np.less(a, b), np.less_equal(a, b), np.greater(a, b), np.greater_equal(a, b)`

In [8]:
np.less_equal(np.array([5, 10, 15]), np.array([15, 10 ,5]))

array([ True,  True, False], dtype=bool)

#### Pairwise logical operation
`a | b, a & b, a ^ b, ~a`

In [9]:
np.array([True, False, True]) ^ np.array([True, True, False])

array([False,  True,  True], dtype=bool)

`np.logical_or(a, b), np.logical_and(a, b), np.logical_xor(a, b), np.logical_not(a, b)`

In [10]:
np.logical_xor(np.array([True, False, True]), np.array([True, True, False]))

array([False,  True,  True], dtype=bool)

#### Floor and ceiling
`np.floor(x), np.ceiling(x)`

In [11]:
np.floor(np.array([1.3, 2.0, 4.2]))

array([ 1.,  2.,  4.])

#### Return each element rounded to the given number of decimals
`np.round(x, n)`

In [12]:
np.round(np.array([1.33, 2.93, 4.25]), 1)

array([ 1.3,  2.9,  4.2])

`round(n)`

In [13]:
np.array([1.33, 2.93, 4.25]).round(1)

array([ 1.3,  2.9,  4.2])

#### Outer product
`np.outer(a, b)`

In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.outer(a, b)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

#### Inner product
`np.inner(a, b)`

In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.inner(a, b)

32

`np.dot(a, b)`

In [16]:
np.dot(a, b)

32

`a.dot(b)`

In [17]:
a.dot(b)

32

#### Universal arithmatic functions
`np.abs(x), np.sin(x), np.cos(x), np.tan(x), np.exp(x), np.exp2(x), np.power(n, x)`

In [18]:
x = np.array([1, 2, 3])
np.abs(x), np.sin(x), np.cos(x), np.tan(x), np.exp(x), np.exp2(x), np.power(1, x)

(array([1, 2, 3]),
 array([ 0.84147098,  0.90929743,  0.14112001]),
 array([ 0.54030231, -0.41614684, -0.9899925 ]),
 array([ 1.55740772, -2.18503986, -0.14254654]),
 array([  2.71828183,   7.3890561 ,  20.08553692]),
 array([ 2.,  4.,  8.]),
 array([1, 1, 1]))

#### Return the cumulative sum of the NumPy array
`cumsum(axis)`: 0 for column, 1 for row (default: all elements)

In [19]:
data = [[10, 5, 15], [3, 9, 6]]
np.array(data)

array([[10,  5, 15],
       [ 3,  9,  6]])

In [20]:
np.array(data).cumsum(0)

array([[10,  5, 15],
       [13, 14, 21]])

#### Repeat universal arithmatic function with binary input
`np.func.reduce(array)`<br>
_e.g. 5 + 10 + 15_

In [21]:
x = np.array([5, 10, 15])
np.add.reduce(x)

30

e.g. _5 \* 10 \* 15_

In [22]:
np.multiply.reduce(x)

750

#### Accumulate the result of repeat universal arithmatic function with binary input
`np.ufunc.accumulate(array)`<br>
_e.g. 5 + 10 + 15_

In [23]:
x = np.array([5, 10, 15])
np.add.accumulate(x)

array([ 5, 15, 30])

In [24]:
np.multiply.accumulate(x)

array([  5,  50, 750])