## Arithmetic
#### Import package

In [1]:
import numpy as np

#### Pairwise calculation by operator
`a + b, a - b, a * b, a / b, a ** b, a % b`

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [3]:
a + b, a - b, a * b, a / b, a ** b, a % b

(array([5, 7, 9]),
 array([-3, -3, -3]),
 array([ 4, 10, 18]),
 array([ 0.25,  0.4 ,  0.5 ]),
 array([  1,  32, 729]),
 array([1, 2, 3]))

#### Pairwise calculation by universal functions
`np.add(a, b), np.subtract(a, b), np.multiply(a, b), np.divide(a, b), np.power(a, b), np.mod(a, b)`

In [4]:
np.add(a, b), np.subtract(a, b), np.multiply(a, b), np.divide(a, b), np.power(a, b), np.mod(a, b)

(array([5, 7, 9]),
 array([-3, -3, -3]),
 array([ 4, 10, 18]),
 array([ 0.25,  0.4 ,  0.5 ]),
 array([  1,  32, 729]),
 array([1, 2, 3]))

#### Outer product
`np.outer(a, b)`

In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.outer(a, b)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

#### Inner product
`np.inner(a, b)`

In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.inner(a, b)

32

`np.dot(a, b)`

In [7]:
np.dot(a, b)

32

`a.dot(b)`

In [8]:
a.dot(b)

32

#### Universal arithmatic functions
`np.abs(x), np.sin(x), np.cos(x), np.tan(x), np.exp(x), np.exp2(x), np.power(n, x)`

In [9]:
x = np.array([1, 2, 3])
np.abs(x), np.sin(x), np.cos(x), np.tan(x), np.exp(x), np.exp2(x), np.power(1, x)

(array([1, 2, 3]),
 array([ 0.84147098,  0.90929743,  0.14112001]),
 array([ 0.54030231, -0.41614684, -0.9899925 ]),
 array([ 1.55740772, -2.18503986, -0.14254654]),
 array([  2.71828183,   7.3890561 ,  20.08553692]),
 array([ 2.,  4.,  8.]),
 array([1, 1, 1]))

#### Repeat universal arithmatic function with binary input
`np.func.reduce(array)`<br>
_e.g. 5 + 10 + 15_

In [10]:
x = np.array([5, 10, 15])
np.add.reduce(x)

30

e.g. _5 \* 10 \* 15_

In [11]:
np.multiply.reduce(x)

750