## Construction
#### Import NumPy package

In [1]:
import numpy as np

#### Create NumPy array using existed list
`np.array(list)`

In [2]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

#### Create NumPy array with zeros
`np.zeros(size)`

In [3]:
np.zeros(5) 

array([ 0.,  0.,  0.,  0.,  0.])

#### Create NumPy array with ones
`np.ones(size)`

In [4]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

#### Create NumPy array with specific element
`np.full(size, element)`

In [5]:
np.full(5, 10)

array([10, 10, 10, 10, 10])

#### Create NumPy array for every _n_ numbers from _a_ to _b_
`np.arange(a, b, n)`

In [6]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

#### Create NumPy array for evenly spaced numbers from _a_ to _b_
`np.linspace(a, b, space)`

In [7]:
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

#### Create NumPy array of random real number from 0 to 1
`np.random.random(size)`

In [8]:
np.random.random(5)

array([ 0.87557065,  0.61985541,  0.10210487,  0.476664  ,  0.08145668])

#### Create NumPy array of random integer from _a_ to _b_
`np.random.randint(a, b, size)`

In [9]:
np.random.randint(0, 1, 5)

array([0, 0, 0, 0, 0])

#### Create NumPy array of normal distribution with mean _a_ and standard deviation _b_
`np.random.normal(a, b, size)`

In [10]:
np.random.normal(0, 1, 5)

array([-1.69465544,  1.45567042,  0.58024478, -1.16411327,  1.01040365])

#### Change data type of NumPy array ([Data Type in NumPy](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html))
`dtype=data_type`

In [11]:
print(np.ones(5).dtype)
print(np.ones(5, dtype=np.int16).dtype)

float64
int16


#### Change the dimension of NumPy array
`size=(a, b, c...)`

In [12]:
np.ones((3, 5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])