## Index
#### Import package

In [1]:
import numpy as np

#### Access array elements using basic index
`x[i]`

In [2]:
x = np.array([4, 3, 2, 1, 0])
x[3]

1

In [3]:
x[-1]

0

In [4]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x[1, 2]

6

#### Change the element in the NumPy array using basic index
`x[i] = n`

In [5]:
x = np.array([4, 3, 2, 1, 0])
x[2] = 10
x

array([ 4,  3, 10,  1,  0])

<b>warning</b>: the data type of the NumPy array will not be change

In [6]:
x[2] = 2.5
x

array([4, 3, 2, 1, 0])

#### Splice NumPy array
`x[start:end:step]` (default: `x[0:size:1]`)

In [7]:
x[0:5:2]

array([4, 2, 0])

In [8]:
x[2:]

array([2, 1, 0])

In [9]:
x[:2]

array([4, 3])

In [10]:
x[::2]

array([4, 2, 0])

#### Access array elements which meet certain condition
`x[condition]`

In [11]:
x = np.array([4, 3, 2, 1, 0])
x[(x < 4) & (x > 1)]

array([3, 2])

In [12]:
x[~(x > 2)]

array([2, 1, 0])

#### Access array elements using Fancy Index
`x[index_array]`

In [13]:
ind = np.array([1, 2, 3])
x[ind]

array([3, 2, 1])

<b>warning</b>: the shape of the returned array is the same with index_array

In [14]:
x = np.arange(12)
ind = np.array([[0, 1], [4, 5], [8, 9]])
x[ind]

array([[0, 1],
       [4, 5],
       [8, 9]])

#### Change the element in the NumPy array using Fancy Index
`x[index_array] = n`

In [15]:
x = np.array([4, 3, 2, 1, 0])
ind = np.array([1, 2, 3])
x[ind] = -1
x

array([ 4, -1, -1, -1,  0])