## [Manipulation](https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html)
#### Import package

In [1]:
import numpy as np

#### Reshape NumPy array
`reshape(shape)`

In [2]:
np.array([[1, 2, 3], [4, 5, 6]]).reshape((3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])

_reshape to 2-D array_

In [4]:
np.array([[1, 2, 3], [4, 5, 6]]).reshape((1, 6))

array([[1, 2, 3, 4, 5, 6]])

_reshape to 1-D array_

In [5]:
np.array([[1, 2, 3], [4, 5, 6]]).reshape((6,))

array([1, 2, 3, 4, 5, 6])

#### Delete elements in array
`np.delete(array, index_list, axis)`

In [23]:
x = np.array([1, 2, 3 ,4, 5])
np.delete(x, [1, 3])

array([1, 3, 5])

_remove specific rows_

In [25]:
x = np.array([[1, 2, 3], [3, 2 ,1], [4, 5, 6], [6, 5, 4]])
np.delete(x, [1, 3], 0)

array([[1, 2, 3],
       [4, 5, 6]])

_remove specific columns_

In [26]:
x = np.array([[1, 2, 3], [3, 2 ,1], [4, 5, 6], [6, 5, 4]])
np.delete(x, [0, 2], 1)

array([[2],
       [2],
       [5],
       [5]])

#### Insert elements to array
`np.insert(array, index, elements, axis)`<br>
<b>warning</b>: the element will be insert before the given index

In [29]:
x = np.array([1, 2, 5])
np.insert(x, 2, [3, 4])

array([1, 2, 3, 4, 5])

_insert elements in high dimensional array_

In [32]:
x = np.array([[1, 2, 3], [3, 2 ,1], [4, 5, 6], [6, 5, 4]])
np.insert(x, 1, [0, -1, -2, -3], axis=1)

array([[ 1,  0,  2,  3],
       [ 3, -1,  2,  1],
       [ 4, -2,  5,  6],
       [ 6, -3,  5,  4]])

In [34]:
np.insert(x, 2, [0, -1, -2], axis=0)

array([[ 1,  2,  3],
       [ 3,  2,  1],
       [ 0, -1, -2],
       [ 4,  5,  6],
       [ 6,  5,  4]])

#### Array concatenation
`np.concatenate(array_list, axis)`: 0 for column (default), 1 for row

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
np.concatenate([a, b, c])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a = np.array([[1, 2, 3], [3, 2 ,1]])
b = np.array([[4, 5, 6], [6, 5, 4]])
np.concatenate([a, b], axis=0)

array([[1, 2, 3],
       [3, 2, 1],
       [4, 5, 6],
       [6, 5, 4]])

In [11]:
a = np.array([[1, 2, 3], [3, 2 ,1]])
b = np.array([[4, 5, 6], [6, 5, 4]])
np.concatenate([a, b], axis=1)

array([[1, 2, 3, 4, 5, 6],
       [3, 2, 1, 6, 5, 4]])

#### Array concatenation by row
`np.vstack(array_list)`

In [12]:
a = np.array([[1, 2, 3], [3, 2 ,1]])
b = np.array([[4, 5, 6], [6, 5, 4]])
np.vstack([a, b])

array([[1, 2, 3],
       [3, 2, 1],
       [4, 5, 6],
       [6, 5, 4]])

#### Array concatenation by column
`np.hstack(array_list)`

In [13]:
a = np.array([[1, 2, 3], [3, 2 ,1]])
b = np.array([[4, 5, 6], [6, 5, 4]])
np.hstack([a, b])

array([[1, 2, 3, 4, 5, 6],
       [3, 2, 1, 6, 5, 4]])

#### Split array
`np.split(array, split_index_array)`

In [17]:
x = np.array([1, 2, 3, 4, 5, 6, 7])
x1, x2, x3, x4 = np.split(a, [2, 4, 6])
x1, x2, x3, x4

(array([1, 2]), array([3, 4]), array([5, 6]), array([7]))

#### Split array by row
`np.vsplit(array, split_index_array)`

In [19]:
x = np.array([[1, 2, 3], [3, 2 ,1], [4, 5, 6], [6, 5, 4]])
x1, x2 = np.vsplit(x, [2])
x1, x2

(array([[1, 2, 3],
        [3, 2, 1]]), array([[4, 5, 6],
        [6, 5, 4]]))

#### Split array by column
`np.hsplit(array, split_index_array)`

In [21]:
x = np.array([[1, 2, 3, 4], [4, 3, 2 ,1]])
x1, x2 = np.hsplit(x, [2])
x1, x2

(array([[1, 2],
        [4, 3]]), array([[3, 4],
        [2, 1]]))