## [Methods](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ndarray.html)
#### Import package

In [1]:
import numpy as np

#### Check if all the elements in the NumPy array are True
`all(axis)`: 0 for column, 1 for row (default: all elements)

In [2]:
data = [[True, False, True], [True, False, True]]
np.array(data)

array([[ True, False,  True],
       [ True, False,  True]], dtype=bool)

In [3]:
np.array(data).all(0)

array([ True, False,  True], dtype=bool)

#### Check if any of the elements in the NumPy array is True
`any(axis)`: 0 for column, 1 for row (default: all elements)

In [4]:
np.array(data).any(1)

array([ True,  True], dtype=bool)

#### Return the indices of the maximum or minimum value in the NumPy array
`argmax(axis)`, 
`argmin(axis)`<br>
0 for column, 1 for row (default: all elements)

In [5]:
data = [[10, 5, 15], [3, 9, 6]]
np.array(data)

array([[10,  5, 15],
       [ 3,  9,  6]])

In [6]:
np.array(data).argmax()

2

In [7]:
np.array(data).argmax(0)

array([0, 1, 0])

In [8]:
np.array(data).argmin(1)

array([1, 0])

#### Return the indices which sort the NumPy array
`argsort(axis)`: 0 for column, 1 for row (default)

In [9]:
np.array(data).argsort()

array([[1, 0, 2],
       [0, 2, 1]])

#### Sort NumPy array
`sort(axis)`: 0 for column, 1 for row (default)<br>
<b>warning</b>: this function will not return a new array

In [10]:
a = np.array([[15, 5, 10], [9, 6, 3]])
a.sort()
a

array([[ 5, 10, 15],
       [ 3,  6,  9]])

#### Change the data type of the NumPy array
`astype(data_type)`

In [11]:
np.array([1.0, 2.5, 3.0]).astype(np.int16)

array([1, 2, 3], dtype=int16)

#### Return the copy of the NumPy array
`copy()`

In [12]:
np.array([1, 2, 3]).copy()

array([1, 2, 3])

#### Return the transpose of the NumPy array
`transpose()`

In [13]:
np.array([[1, 2, 3], [4, 5, 6]]).transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])