## [Universal functions](https://docs.scipy.org/doc/numpy-1.15.1/reference/ufuncs.html)
#### Import package

In [1]:
import numpy as np

#### Count non-zero elements
`np.count_nonzero(array)`

In [2]:
np.count_nonzero(np.array([0, 1, 2]))

2

#### Check if any of the elements in the NumPy array is True
`np.any(array, axis)`: 0 for column, 1 for row (default: all elements)

In [3]:
np.any(np.array([0, 1, 2]) > 1)

True

#### Check if all of the elements in the NumPy array are True
`np.all(array, axis)`: 0 for column, 1 for row (default: all elements)

In [4]:
np.all(np.array([0, 1, 2]) > 1)

False

#### Check element-wise for finite number
`np.isfinite(array)`

In [5]:
np.isfinite(np.array([1, 2, np.inf]))

array([ True,  True, False], dtype=bool)

#### Check element-wise for infinite number
`np.isinf(array)`

In [6]:
np.isinf(np.array([1, 2, np.inf]))

array([False, False,  True], dtype=bool)

#### Check element-wise for NaN
`np.isnan(array)`

In [7]:
np.isnan(np.array([1, 2, np.nan]))

array([False, False,  True], dtype=bool)